# Generated by Django 3.2.9 on 2022-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Eduction', models.CharField(max_length=200)),
                ('Contry', models.CharField(max_length=200)),
                ('Ethnicity', models.CharField(max_length=200)),
                ('Nscore', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Escore', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Oscore', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Ascore', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Cscore', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Impulsive', models.DecimalField(decimal_places=5, max_digits=7)),
                ('SS', models.DecimalField(decimal_places=5, max_digits=7)),
                ('model_result', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
